# Generated by Django 3.2.9 on 2021-12-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('technology', models.CharField(max_length=250)),
                ('head', models.CharField(max_length=250)),
                ('members', models.IntegerField(default=0)),
                ('hours', models.IntegerField()),
            ],
            options={
                'db_table': 'forum',
            },
        ),
    ]
