# Generated by Django 3.2.9 on 2021-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='members',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
