# Generated by Django 3.2.9 on 2021-12-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_alter_forum_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='members',
            field=models.IntegerField(null=True),
        ),
    ]
